// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RoutesLazyImport = createFileRoute('/routes')()
const ClientsLazyImport = createFileRoute('/clients')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RoutesLazyRoute = RoutesLazyImport.update({
  path: '/routes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/routes.lazy').then((d) => d.Route))

const ClientsLazyRoute = ClientsLazyImport.update({
  path: '/clients',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/clients.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/clients': {
      preLoaderRoute: typeof ClientsLazyImport
      parentRoute: typeof rootRoute
    }
    '/routes': {
      preLoaderRoute: typeof RoutesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ClientsLazyRoute,
  RoutesLazyRoute,
])
